line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ### works up until this config rule
  ignores_interpolated_strings: true

identifier_name:
  excluded:
    - v
    - t
    - s
    - c
    - b
    - d
    - i
    - h
    - el
    - bn
    - to
    - id
    - tx
    - vc
    - ok

excluded:
  - Pods
  - .build
  - Tests